// words.js
// The built-in flashcard deck: common Spanish words/phrases for beginners.
// Kept separate from app logic (script.js) so the deck is easy to read,
// edit, or extend later. Each word has a stable "id" so progress saved in
// localStorage stays matched to the right word even if the array order
// changes.

const WORD_DECK = [
  { id: 1, spanish: "hola", english: "hello" },
  { id: 2, spanish: "adiós", english: "goodbye" },
  { id: 3, spanish: "gracias", english: "thank you" },
  { id: 4, spanish: "por favor", english: "please" },
  { id: 5, spanish: "sí", english: "yes" },
  { id: 6, spanish: "no", english: "no" },
  { id: 7, spanish: "amigo", english: "friend (male)" },
  { id: 8, spanish: "amiga", english: "friend (female)" },
  { id: 9, spanish: "familia", english: "family" },
  { id: 10, spanish: "casa", english: "house" },
  { id: 11, spanish: "agua", english: "water" },
  { id: 12, spanish: "comida", english: "food" },
  { id: 13, spanish: "perro", english: "dog" },
  { id: 14, spanish: "gato", english: "cat" },
  { id: 15, spanish: "libro", english: "book" },
  { id: 16, spanish: "escuela", english: "school" },
  { id: 17, spanish: "trabajo", english: "work / job" },
  { id: 18, spanish: "tiempo", english: "time / weather" },
  { id: 19, spanish: "día", english: "day" },
  { id: 20, spanish: "noche", english: "night" },
  { id: 21, spanish: "mañana", english: "morning / tomorrow" },
  { id: 22, spanish: "tarde", english: "afternoon / late" },
  { id: 23, spanish: "año", english: "year" },
  { id: 24, spanish: "semana", english: "week" },
  { id: 25, spanish: "hombre", english: "man" },
  { id: 26, spanish: "mujer", english: "woman" },
  { id: 27, spanish: "niño", english: "boy / child" },
  { id: 28, spanish: "niña", english: "girl" },
  { id: 29, spanish: "grande", english: "big" },
  { id: 30, spanish: "pequeño", english: "small" },
  { id: 31, spanish: "bueno", english: "good" },
  { id: 32, spanish: "malo", english: "bad" },
  { id: 33, spanish: "feliz", english: "happy" },
  { id: 34, spanish: "triste", english: "sad" },
  { id: 35, spanish: "caliente", english: "hot" },
  { id: 36, spanish: "frío", english: "cold" },
  { id: 37, spanish: "comer", english: "to eat" },
  { id: 38, spanish: "beber", english: "to drink" },
  { id: 39, spanish: "hablar", english: "to speak" },
  { id: 40, spanish: "caminar", english: "to walk" },
  { id: 41, spanish: "correr", english: "to run" },
  { id: 42, spanish: "dormir", english: "to sleep" },
  { id: 43, spanish: "leer", english: "to read" },
  { id: 44, spanish: "escribir", english: "to write" },
  { id: 45, spanish: "amor", english: "love" },
  { id: 46, spanish: "dinero", english: "money" },
  { id: 47, spanish: "coche", english: "car" },
  { id: 48, spanish: "ciudad", english: "city" },
  { id: 49, spanish: "país", english: "country" },
  { id: 50, spanish: "mundo", english: "world" },
];
